#Use "%player%" to define the player's name. 
#For Color/Formatting Codes http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes

#Define a global custom join message.
Message: '%player% joined'

#Define a global custom quit message.
QuitMessage: '%player% left'

#Define Custom Join/Quit Messages for Groups
Group:
  Admin:
    Message: 'Admin %player% joined'
    QuitMessage: 'Admin %player% left'
    
#Define Custom Join/Quit Messages for Players
Player:
  tacticalsk8er:
    Message: 'The developer of Join Message has joined!'
    QuitMessage: 'The developer of Join Message has left!'

#If true, plugin will use group messages.
Groups: false

#If true, plugin will use player messages.

#If true, plugin will add prefixs to messages.
Prefix: false

#If true, plugin will add suffixs to messages.
Suffix: false
