#JoinMessage © 2013 created by tacticalsk8er
#Use "%player%" to define the player's name. 

#This is where you define a custom join message.
Message: '%player% joined'
  Admin: '%player% joined, warning he is an admin!'
#This is where you define a custom quit message.
QuitMessage: '%player% left'
  Admin: '%player% left, you can now relax'
#Set to true if you want to enable group based join messages.
Groups: false
