name: JoinMessage
main: me.tacticalsk8er.JoinMessage.Main
author: tacticalsk8er
version: 2.3
description: Changes the default join message with a customized one.
softdepend: [Vault]

commands:
  jm:
    description: Prefix to most commands in Join Message
    permission-message: You do not have permission to use this!
    usage: /jm ?
    

permissions:
  jm.silent:
    description: Allows you to join/leave the server without a join/leave message.
    default: false
    children:
      jm.silentjoin: true
      jm.silentquit: true
  jm.silentjoin:
    description: Allows you to join the server without a join message.
    default: false
  jm.silentquit:
    description: Allows you to leave the server without a leave message.
    default: false
  jm.reload:
    description: Allows you to use /jm reload.
    default: op
  jm.set:
    description: Allows you to use /jm set.
    default: op
  jm.set.group:
    description: Allows you to use /jm group.
    default: op
  jm.set.player:
    description: Allows you to use /jm player.
    default: op
  jm.help:
    description: Allows you to use /jm help and /jm ?.
    default: op
  jm.info:
   description: Allows you to use /jm info.
   default: op
